apiVersion: v1
kind: Service
metadata:
  name: g2n-serving
spec:
  selector:
    app: g2n
    component: serving
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: g2n-dashboard
spec:
  selector:
    app: g2n
    component: dashboard
  ports:
    - name: http
      port: 80
      targetPort: 8501
  type: ClusterIP
